post http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"uop789",
    "name":"Zhe He",
    "password":"hz888190123"
}

# {
#     "username":"uop123",
#     "name":"Heather He",
#     "password":"hz888190234"
# }